// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_tdd_q/test/common/auth/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_tdd_q/common/domain/models/user_credentials.dart'
    as _i2;
import 'package:flutter_tdd_q/features/auth/data/datasources/auth_local_data_source.dart'
    as _i5;
import 'package:flutter_tdd_q/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserCredentials_0 extends _i1.Fake implements _i2.UserCredentials {}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserCredentials> googleSignIn() =>
      (super.noSuchMethod(Invocation.method(#googleSignIn, []),
              returnValue:
                  Future<_i2.UserCredentials>.value(_FakeUserCredentials_0()))
          as _i4.Future<_i2.UserCredentials>);
  @override
  _i4.Future<dynamic> googleSignOut() =>
      (super.noSuchMethod(Invocation.method(#googleSignOut, []),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<bool> isRegistrationComplete() =>
      (super.noSuchMethod(Invocation.method(#isRegistrationComplete, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i5.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> storeUserCredentials(
          _i2.UserCredentials? userCredentials) =>
      (super.noSuchMethod(
          Invocation.method(#storeUserCredentials, [userCredentials]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<_i2.UserCredentials> getUserCredentials() =>
      (super.noSuchMethod(Invocation.method(#getUserCredentials, []),
              returnValue:
                  Future<_i2.UserCredentials>.value(_FakeUserCredentials_0()))
          as _i4.Future<_i2.UserCredentials>);
}
